### ISSUE TITLE
feat: Infer the type for attributes from the assigned value with mypy

### ISSUE THREAD

**Issue by Masara** [Safe-DS/Stub-Generator#34]
### Is your feature request related to a problem?

Attributes, parameters and results in stubs, which are generated from python code, currently have no type information if the python code did not have type hints. Example:
```py
# Python Code
class A:
    attr1: int
    attr2 = 2

    def my_func(a = 1):
        return a
```

```
// Safe-DS stubs
class A() {
    attr1: Int
    attr2

    fun myFunc(a = 1) -> result1: Any
}    
```

Furthermore, currently, if a function has no return type specified, the API will generate "Any" as the return type. This value has to be removed and the type has to be either inferred with mypy or left empty.

### Desired solution

The API Class has to be adjusted to also infer type information with mypy if no type hints are given.
Then the following should be done:

1. Try to infer the type from the assigned value if mypy offers this functionality.
```
// Safe-DS stubs
class A() {
    attr1: Int
    attr2: Int

    fun myFunc(a: Int = 1) -> result1: Int
}    
```

2. If this is not possible (in general or for a specific case) add a TODO.
```
// Safe-DS stubs
class A() {
    attr1: Int
    // TODO Attribute has no type information.
    attr2

    // TODO Parameter has no type information.
    // TODO Result has no type information.
    fun myFunc(a) -> result1
}    
```

**Comment by Masara** [comment]
@lars-reimann Do we also want to infer parameter and result types?

**Comment by lars-reimann** [comment]
Yes to both. Later we can compare this with the information in the documentation.

**Comment by Masara** [comment]
@lars-reimann
1. For parameter default values and type hint, what kind of values do we support in Safe-DS? You once told me that we only support float, int, bool, str and None. Should I therefore ignore other types?
2. Mypy can't infer default values of attributes in __init__ methods. Should I add "Type hint missing ..." todo messages none the less?

**Comment by lars-reimann** [comment]
> 1. Default values can be any [expression](https://dsl.safeds.com/en/stable/language/pipeline-language/expressions/). Types could be any [core class](https://github.com/Safe-DS/DSL/blob/main/packages/safe-ds-lang/src/resources/builtins/safeds/lang/coreClasses.sdsstub) or any type for which you created stubs.

> 2. Mypy can't infer default values of attributes in __init__ methods. Should I add "Type hint missing ..." todo messages none the less?

Yes, and leave the type empty.

**Comment by Masara** [comment]
@lars-reimann If we have function like this:
```py
def func(self):
    if ...:
        return 1
    elif ...:
        return bool
    else:
        return 1.2, "some string"
```
how would the result information for the stubs look like?

**Comment by Masara** [comment]
@lars-reimann Would it be
```
fun func() -> (result1: Union<Int, Boolean, Float>, result2: String?)
```
?

**Comment by lars-reimann** [comment]
For `result1`, we could set the type to:

* `Any` (common supertype of the possible types in the union)
* `union<Int, Boolean, Float>`
* `literal<42, false, 1.2>` (the exact possible values)

For now, I don't have a clear preference towards either option. Do whatever is easiest with `mypy`.

**Comment by Masara** [comment]
This issue is finished. This is a summary of some things, that Mypy could not handle:
1. Mypy can't infer default values of attributes in init methods.
2. Mypy can't infer the default value if its a call expression like ```some_attr = SomeClass()```
