### ISSUE TITLE
feat: Add variance handling for the stubs generator.

### ISSUE THREAD

**Issue by Masara** [Safe-DS/Stub-Generator#35]
### Is your feature request related to a problem?

Currently code with variances is not handled during the stubs generation. If possible, this feature should be added.

### Desired solution

In Python variance is [inferred](https://peps.python.org/pep-0695/#summary), therefor, if possible with Mypy, it should be inferred and added to the stubs generator.

### Additional Context (optional)

* https://dsl.safeds.com/en/latest/language/common/variance/
* https://github.com/Safe-DS/DSL/blob/4c61b8c18a50fc89f193ebbbaa66ef1743db9ee0/tests/resources/grammar/declarations/classes/good-covariant%20type%20parameter.sdstest
* https://github.com/Safe-DS/DSL/blob/4c61b8c18a50fc89f193ebbbaa66ef1743db9ee0/tests/resources/grammar/declarations/classes/good-contravariant%20type%20parameter.sdstest
* https://peps.python.org/pep-0695/#summary

**Comment by Masara** [comment]
@lars-reimann With issue #36 we are able to create stubs like these:
```py
# Python Code
_T_co = TypeVar("_T_co", covariant=True, bound=str)
_T_con = TypeVar("_T_con", contravariant=True, bound=int)

class ClassA(Generic[_T_co, _T_con]):
        ...
```

```
# Safe-DS stubs
class ClassA<out TCo, in TCon> where {
    TCo sub String,
    TCon super Int
}
```

Therefore, this Issue is also already finished, right? Or am I mixing variance and constrains up?

**Comment by lars-reimann** [comment]
You can naturally handle constraints and variance in one go, but they are different concepts:

Variance:
* Python `covariance=True` -> Safe-DS `out`
* Python `contravariance=True` -> Safe-DS `in`
* Python neither -> Safe-DS no modifier

Bounds/constraints:
* Python `bound=...` -> Safe-DS `where` block with type parameter constraints

**Comment by Masara** [comment]
Since I handled both concepts already in issue #36 I will close this issue.
