### ISSUE TITLE
feat: Add contrains handling for stubs generator.

### ISSUE THREAD

**Issue by Masara** [Safe-DS/Stub-Generator#36]
### Is your feature request related to a problem?

Currently code with contrains is not handled during the stubs generation. If possible, this feature should be added (Python only supports upper bound contrains).

### Desired solution

```py
# Python
class ClassA[T: str]:
	...
```

```
// Stubs
class ClassA<T> where {T sub String} {
	...
}
```

### Additional Context (optional)

* https://peps.python.org/pep-0695/#upper-bound-specification
* https://peps.python.org/pep-0695/#summary
* https://github.com/Safe-DS/DSL/blob/4c61b8c18a50fc89f193ebbbaa66ef1743db9ee0/tests/resources/grammar/declarations/classes/good-with%20multiple%20constraints.sdstest

**Comment by Masara** [comment]
@lars-reimann It seems that Mypy is unable to parse constrains of the form
```python
class A[T: str]: ...
```

I found the mypy module ```constraints.py```, but there another form of constrain definition is explained:
```python
class Constraint:
    """A representation of a type constraint.

    It can be either T <: type or T :> type (T is a type variable).
    """
   ...
```
But it seems like it is just an internal constrains solver, not a parser we could use.

**Comment by lars-reimann** [comment]
OK, let's defer this issue for now.

**Comment by Masara** [comment]
@lars-reimann Yes, mypy can handle this syntax. I will create a parser for this syntax.
How would invariance be defined? Like this:
```python
_T_in = TypeVar("_T_in", str, int)
```
?

**Comment by lars-reimann** [comment]
Probably, yes. Regarding this issue, I was rather looking at the `bound=str` part, though.

**Comment by Masara** [comment]
So, if we parse this code:
```python
_T_co = TypeVar("_T_co", covariant=True, bound=str)
_T_con = TypeVar("_T_con", contravariant=True, bound=int)


class ClassA(Generic[_T_co, _T_con]):
    def method1(self) -> _T_co:
        ...
```

would it result in these stubs
```
class ClassA where {
    PythonName("_T_co") TCo sub str,
    PythonName("_T_con") TCon super int
}
```
?

And invariance is not of importance for us, since its the standard case?

**Comment by Masara** [comment]
@lars-reimann So, if we parse this code:
```python
_T_co = TypeVar("_T_co", covariant=True, bound=str)
_T_con = TypeVar("_T_con", contravariant=True, bound=int)


class ClassA(Generic[_T_co, _T_con]):
    def method1(self) -> _T_co:
        ...
```

would it result in these stubs
```
class ClassA where {
    PythonName("_T_co") TCo sub str,
    PythonName("_T_con") TCon super int
}
```
?

And invariance is not of importance for us, since its the standard case?

**Comment by lars-reimann** [comment]
No, the stubs would be

```
class ClassA<TCo, TCon> where {
    TCo sub str,
    TCon super int
}
```

You first have to declare the type parameters (in the <> after the class name) and can omit the `@PythonName` in this case, since we handle all type checking in `Safe-DS` and don't have to translate the type parameters back to Python.

**Comment by Masara** [comment]
@lars-reimann Could you also give me an example of a class with constructor parameters? I dont know where the curved brackets

**Comment by lars-reimann** [comment]
The `v0.3.0` release of the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=safe-ds.safe-ds) has snippets. The `class` snippet generates the skeleton of a class:

![image](https://github.com/Safe-DS/Stub-Generator/assets/2501322/1fd64c4e-d4ac-4fa4-9674-fd109af9f727)

Slightly reformatted & without a superclass:

```
class MyClass<>() where {
    // ...
} {
   // ...
}
```
