### ISSUE TITLE
feat: Generate stubs for public methods of private classes which are superclasses of public classes

### ISSUE THREAD

**Issue by Masara** [Safe-DS/Stub-Generator#64]
### Is your feature request related to a problem?

Currently (after PR #50), if public classes inherit from private classes, the stubs for the public class will be generated and reference those private classes, but the private classes won't be generated and are therefore "invisible" for the user.

### Desired solution

~~If a public class inherits from a private class, the private class should generate stubs, too.~~

~~To do this, we would need to extend the information in the API data so that superclass information also points in the other direction, i.e. we need to find out the subclasses for all classes.~~

The stubs generator should add the public methods of the internal classes to the public classes.

### Additional Context

An example test case where the private super class should be generated can be found @ ```Stub-Generator\tests\data\various_modules_package\aliasing\aliasing_module_1.py``` for the class ```AliasingModuleClassC```.

**Comment by Masara** [comment]
An example test case where the private super class should be generated can be found @ ```Stub-Generator\tests\data\various_modules_package\aliasing\aliasing_module_1.py``` for the class ```AliasingModuleClassC```.

**Comment by lars-reimann** [comment]
I'd rather propose to generate stubs for inherited public methods in the public classes. The stubs are meant to mirror the *public* interface of a library, which internal classes are not a part of.
